/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperusersRouteImport } from './routes/_authenticated.superusers'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as ApiPublicSupabaseConfigRouteImport } from './routes/api/public/supabase-config'
import { Route as AuthenticatedMembersTenantIdRouteImport } from './routes/_authenticated.members.$tenantId'
import { Route as AuthenticatedAuditTenantIdRouteImport } from './routes/_authenticated.audit.$tenantId'
import { Route as AuthenticatedAppTenantIdRouteImport } from './routes/_authenticated.app.$tenantId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperusersRoute = AuthenticatedSuperusersRouteImport.update({
  id: '/superusers',
  path: '/superusers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSupabaseConfigRoute = ApiPublicSupabaseConfigRouteImport.update({
  id: '/api/public/supabase-config',
  path: '/api/public/supabase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMembersTenantIdRoute =
  AuthenticatedMembersTenantIdRouteImport.update({
    id: '/members/$tenantId',
    path: '/members/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditTenantIdRoute =
  AuthenticatedAuditTenantIdRouteImport.update({
    id: '/audit/$tenantId',
    path: '/audit/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppTenantIdRoute =
  AuthenticatedAppTenantIdRouteImport.update({
    id: '/app/$tenantId',
    path: '/app/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/superusers': typeof AuthenticatedSuperusersRoute
  '/app/$tenantId': typeof AuthenticatedAppTenantIdRoute
  '/audit/$tenantId': typeof AuthenticatedAuditTenantIdRoute
  '/members/$tenantId': typeof AuthenticatedMembersTenantIdRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/superusers': typeof AuthenticatedSuperusersRoute
  '/app/$tenantId': typeof AuthenticatedAppTenantIdRoute
  '/audit/$tenantId': typeof AuthenticatedAuditTenantIdRoute
  '/members/$tenantId': typeof AuthenticatedMembersTenantIdRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/superusers': typeof AuthenticatedSuperusersRoute
  '/_authenticated/app/$tenantId': typeof AuthenticatedAppTenantIdRoute
  '/_authenticated/audit/$tenantId': typeof AuthenticatedAuditTenantIdRoute
  '/_authenticated/members/$tenantId': typeof AuthenticatedMembersTenantIdRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/onboarding'
    | '/superusers'
    | '/app/$tenantId'
    | '/audit/$tenantId'
    | '/members/$tenantId'
    | '/api/public/supabase-config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/onboarding'
    | '/superusers'
    | '/app/$tenantId'
    | '/audit/$tenantId'
    | '/members/$tenantId'
    | '/api/public/supabase-config'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/onboarding'
    | '/_authenticated/superusers'
    | '/_authenticated/app/$tenantId'
    | '/_authenticated/audit/$tenantId'
    | '/_authenticated/members/$tenantId'
    | '/api/public/supabase-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicSupabaseConfigRoute: typeof ApiPublicSupabaseConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/superusers': {
      id: '/_authenticated/superusers'
      path: '/superusers'
      fullPath: '/superusers'
      preLoaderRoute: typeof AuthenticatedSuperusersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/supabase-config': {
      id: '/api/public/supabase-config'
      path: '/api/public/supabase-config'
      fullPath: '/api/public/supabase-config'
      preLoaderRoute: typeof ApiPublicSupabaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/members/$tenantId': {
      id: '/_authenticated/members/$tenantId'
      path: '/members/$tenantId'
      fullPath: '/members/$tenantId'
      preLoaderRoute: typeof AuthenticatedMembersTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/$tenantId': {
      id: '/_authenticated/audit/$tenantId'
      path: '/audit/$tenantId'
      fullPath: '/audit/$tenantId'
      preLoaderRoute: typeof AuthenticatedAuditTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$tenantId': {
      id: '/_authenticated/app/$tenantId'
      path: '/app/$tenantId'
      fullPath: '/app/$tenantId'
      preLoaderRoute: typeof AuthenticatedAppTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSuperusersRoute: typeof AuthenticatedSuperusersRoute
  AuthenticatedAppTenantIdRoute: typeof AuthenticatedAppTenantIdRoute
  AuthenticatedAuditTenantIdRoute: typeof AuthenticatedAuditTenantIdRoute
  AuthenticatedMembersTenantIdRoute: typeof AuthenticatedMembersTenantIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSuperusersRoute: AuthenticatedSuperusersRoute,
  AuthenticatedAppTenantIdRoute: AuthenticatedAppTenantIdRoute,
  AuthenticatedAuditTenantIdRoute: AuthenticatedAuditTenantIdRoute,
  AuthenticatedMembersTenantIdRoute: AuthenticatedMembersTenantIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicSupabaseConfigRoute: ApiPublicSupabaseConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
